### ISSUE TITLE
Reading / Writing dataset yamls in jupyter notebook

### ISSUE THREAD

**Issue by seriksen** [FAST-HEP/fast-curator#42]
A datasets created using `fast_curator.write.write_yaml` are not readable by `fast_curator.read.yaml`

Code snippet
```
from fast_curator.write import prepare_file_list, prepare_contents, write_yaml
fileLoc="/global/projecta/projectdirs/lz/data/MDC3/calibration/LZAP-4.5.1/20180226/lz_201802260001_32_lzap.root"
fileList = prepare_file_list(fileLoc,
                             dataset="DD",
                             expand_files="local",
                             tree_name="Scatters",
                             eventtype="mc",
                             no_empty_files=True,
                             confirm_tree=False,
                             ignore_inaccessible=True
                            ) 

datalist = []
datalist.append(fileList)
contents = prepare_contents(datalist)
dataset = get_datasets(contents)

# write out the dataset config file
a = write_yaml(dataset, "dataset.yml", append=False)

dataset_read = read.from_yaml("dataset.yaml")
```
Error is 
```
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:argparse.Namespace'
  in "dataset.yaml", line 2, column 7
```

dataset.yaml looks as
```
datasets:
  - - !!python/object:argparse.Namespace
      associates: []
      eventtype: mc
      files:
        - /global/projecta/projectdirs/lz/data/MDC3/calibration/LZAP-4.5.1/20180226/lz_201802260001_32_lzap.root
      name: DD
      nevents: 639
      nfiles: 1
      tree: Scatters
```

`dataset` is
```
[Namespace(associates=[], eventtype='mc', files=['/global/projecta/projectdirs/lz/data/MDC3/calibration/LZAP-4.5.1/20180226/lz_201802260001_32_lzap.root'], name='DD', nevents=639, nfiles=1, tree='Scatters')]
```
